// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ClientPlugin","status":true,"description":"","parameters":{}},
{"name":"CatGreetingPlugin","status":true,"description":"猫が挨拶してくれるプラグイン","parameters":{}},
{"name":"EventReSpawn","status":true,"description":"イベント動的生成プラグイン","parameters":{"keepSelfSwitch":"false","tryRandomCount":"1000"}},
{"name":"ExecuteMapEvent","status":true,"description":"マップイベントを実行するプラグイン.","parameters":{}},
{"name":"MenuPlugin","status":true,"description":"","parameters":{}}
];
