var m_job_list = [
	{
		rankId: 'JR000',
		rankMei: '無職',
		classId: 'JB000',
		classMei: '無職',
		money: 0,
		morality: 0,
		power: 0,
		intellect: 0,
		sense: 0,
		charm: 0,
		memoSkill: '何もしない。',
		memoJob: '何も求められず、何も得るものがない職業。夢はある。'
	},
	{
		rankId: 'JR010',
		rankMei: '戦士',
		classId: 'JB010',
		classMei: '戦士',
		money: 200,
		morality: 0,
		power: 3,
		intellect: 0,
		sense: 0,
		charm: 0,
		memoSkill: '移動時の消費体力が半分になる。',
		memoJob: '力が求められる職業。魔物を討伐して生計を立てる。'
	},
	{
		rankId: 'JR011',
		rankMei: '勇者',
		classId: 'JB010',
		classMei: '戦士',
		money: 500,
		morality: 2,
		power: 10,
		intellect: 0,
		sense: 0,
		charm: 8,
		memoSkill: '土地の事件を解決し、治安を上昇させる。',
		memoJob: '力が求められる職業。魔物を討伐して生計を立てる。'
	},
	{
		rankId: 'JR012',
		rankMei: '騎士',
		classId: 'JB010',
		classMei: '戦士',
		money: 300,
		morality: 1,
		power: 6,
		intellect: 3,
		sense: 0,
		charm: 0,
		memoSkill: '指名手配犯一人の場所まで移動して捕まえる。',
		memoJob: '力が求められる職業。魔物を討伐して生計を立てる。'
	},
	{
		rankId: 'JR013',
		rankMei: 'スナイパー',
		classId: 'JB010',
		classMei: '戦士',
		money: 800,
		morality: 0,
		power: 20,
		intellect: 15,
		sense: 12,
		charm: 0,
		memoSkill: '付近にいるプレイヤーに致命傷を与えて能力を下げる。',
		memoJob: '力が求められる職業。依頼された人物を撃破して生計を立てる。'
	},
	{
		rankId: 'JR020',
		rankMei: '学者',
		classId: 'JB020',
		classMei: '学者',
		money: 200,
		morality: 0,
		power: 0,
		intellect: 3,
		sense: 0,
		charm: 0,
		memoSkill: '使用するアイテムの効果を少し上げる。',
		memoJob: '知性が求められる職業。道具を売買して生計を立てる。'
	},
	{
		rankId: 'JR021',
		rankMei: '魔術者',
		classId: 'JB020',
		classMei: '学者',
		money: 400,
		morality: 0,
		power: 0,
		intellect: 18,
		sense: 6,
		charm: 0,
		memoSkill: '周辺の土地に災害を起こし、人口を減少させる。',
		memoJob: '知性が求められる職業。魔物を討伐して生計を立てる。'
	},
	{
		rankId: 'JR022',
		rankMei: '薬師',
		classId: 'JB020',
		classMei: '学者',
		money: 400,
		morality: 0,
		power: 0,
		intellect: 10,
		sense: 3,
		charm: 6,
		memoSkill: '付近にいる仲間の体力を回復する。',
		memoJob: '知性が求められる職業。薬を生成して生計を立てる。'
	},
	{
		rankId: 'JR023',
		rankMei: '支配者',
		classId: 'JB020',
		classMei: '学者',
		money: 2000,
		morality: -2,
		power: 8,
		intellect: 30,
		sense: 15,
		charm: 20,
		memoSkill: '土地のレベルを1つ上げる。',
		memoJob: '知性が求められる職業。物資を徴収して生計を立てる。'
	},
	{
		rankId: 'JR030',
		rankMei: '商人',
		classId: 'JB030',
		classMei: '商人',
		money: 200,
		morality: 0,
		power: 0,
		intellect: 0,
		sense: 3,
		charm: 0,
		memoSkill: 'ショップの販売価格が安くなり、売却価格が高くなる。',
		memoJob: 'センスが求められる職業。道具を売買して生計を立てる。'
	},
	{
		rankId: 'JR031',
		rankMei: '技師',
		classId: 'JB030',
		classMei: '商人',
		money: 300,
		morality: 0,
		power: 8,
		intellect: 3,
		sense: 10,
		charm: 0,
		memoSkill: '建設時のコストが安くなる。',
		memoJob: 'センスが求められる職業。道具を生成して生計を立てる。'
	},
	{
		rankId: 'JR032',
		rankMei: '操縦士',
		classId: 'JB030',
		classMei: '商人',
		money: 400,
		morality: 0,
		power: 3,
		intellect: 6,
		sense: 8,
		charm: 0,
		memoSkill: '自分と付近にいる仲間を任意の土地まで移動させる。',
		memoJob: 'センスが求められる職業。道具を生成して生計を立てる。'
	},
	{
		rankId: 'JR033',
		rankMei: '詐欺師',
		classId: 'JB030',
		classMei: '商人',
		money: 1500,
		morality: -1,
		power: 6,
		intellect: 20,
		sense: 25,
		charm: 0,
		memoSkill: '土地の購入と建築のコストを半額にする。',
		memoJob: 'センスが求められる職業。金品を奪って生計を立てる。'
	},
	{
		rankId: 'JR040',
		rankMei: '踊り子',
		classId: 'JB040',
		classMei: '踊り子',
		money: 200,
		morality: 0,
		power: 0,
		intellect: 0,
		sense: 0,
		charm: 3,
		memoSkill: '滞在した土地の特産品を1つもらえる。',
		memoJob: '魅力が求められる職業。夢と希望を与えて生計を立てる。'
	},
	{
		rankId: 'JR041',
		rankMei: 'アイドル',
		classId: 'JB040',
		classMei: '踊り子',
		money: 800,
		morality: 0,
		power: 0,
		intellect: 0,
		sense: 4,
		charm: 10,
		memoSkill: '土地でイベントを催し、人口を上昇させる。',
		memoJob: '魅力が求められる職業。夢と希望を与えて生計を立てる。'
	},
	{
		rankId: 'JR042',
		rankMei: '歌姫',
		classId: 'JB040',
		classMei: '踊り子',
		money: 1000,
		morality: 0,
		power: 0,
		intellect: 6,
		sense: 6,
		charm: 10,
		memoSkill: '2ターンの間、周辺プレイヤーがスキル使用不可になる。',
		memoJob: '魅力が求められる職業。夢と希望を与えて生計を立てる。'
	},
	{
		rankId: 'JR043',
		rankMei: 'せくしー',
		classId: 'JB040',
		classMei: '踊り子',
		money: 1500,
		morality: -1,
		power: 0,
		intellect: 20,
		sense: 8,
		charm: 30,
		memoSkill: '付近にいるプレイヤーを誘惑して所有財産を頂戴する。',
		memoJob: '魅力が求められる職業。金品を謙譲させて生計を立てる。'
	}
];
module.exports = m_job_list;